rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/5.0.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/5.0.gemfile
notifications:
  recipients:
    - weppos@weppos.net
